import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';

type AuthLayoutProps = {
  children: React.ReactNode;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AuthLayout = ({ children }: AuthLayoutProps) => {
  return (
    <html lang="en">
      <body
        className={cn(
          'flex h-screen w-full flex-col md:flex-row',
          inter.className,
        )}
      >
        <section className="hidden w-[40%] flex-col justify-between bg-primary p-4 text-primary-foreground md:flex">
          <h3 className="text-3xl">Travel App</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat
            tenetur maiores doloribus corrupti itaque. Laborum, debitis incidunt
            delectus ipsa, atque itaque dolor qui id nihil quaerat voluptas
            officiis doloremque at similique quas voluptate deleniti. Ipsam,
            quas dolorem! Atque, architecto unde?
          </p>
        </section>
        <section className="flex h-full flex-col items-center justify-center bg-secondary p-4 text-secondary-foreground md:w-[60%]">
          {children}
        </section>
      </body>
    </html>
  );
};

export default AuthLayout;
