import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/sidebar';
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('flex h-screen w-full bg-accent', inter.className)}>
        <Sidebar />
        <section className="w-full">
          <Navbar />
          {children}
        </section>
      </body>
    </html>
  );
}
